//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Recruiters = new HashSet<Recruiter>();
            this.ContractTemplates = new HashSet<ContractTemplate>();
        }
    
        public int ID_COMPANY { get; set; }
        public string COMPANY_NAME { get; set; }
        public string PHONE1 { get; set; }
        public string EMAIL1 { get; set; }
        public string MAPS_URL { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string ZIPCODE { get; set; }
        public string LOGO { get; set; }
        public string CAPTION { get; set; }
        public string CONTENT_TYPE { get; set; }
        public byte[] PROFILE_IMG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recruiter> Recruiters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTemplate> ContractTemplates { get; set; }
    }
}
