//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTemplate
    {
        public int ContractTemplateID { get; set; }
        public string TemplateName { get; set; }
        public string TemplateContent { get; set; }
        public byte[] TemplateContentBlob { get; set; }
        public System.DateTime DateRecord { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
