//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewQuestion
    {
        public int InterviewQuestionID { get; set; }
        public string CreatedBy { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string Technology { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public byte[] DescriptionBlob { get; set; }
    }
}
