//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MockInterview
    {
        public int MockInterviewID { get; set; }
        public Nullable<int> TrainingCourseID { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public int InterviewedBy { get; set; }
        public string Performance { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public int WebsiteUserID { get; set; }
        public string Technology { get; set; }
        public Nullable<int> InterviewedBy2 { get; set; }
        public Nullable<int> InterviewedBy3 { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TrainingCours TrainingCours { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
