//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeSendApproval
    {
        public int ResumeSendApprovalID { get; set; }
        public Nullable<int> ResumeID { get; set; }
        public Nullable<int> WebsiteUserID { get; set; }
        public Nullable<System.DateTime> DateSubmited { get; set; }
        public Nullable<int> SubmitedTo { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> SubmitedFrom { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual WebsiteUser WebsiteUser { get; set; }
        public virtual WebsiteUserResume WebsiteUserResume { get; set; }
    }
}
