//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingCours()
        {
            this.MockInterviews = new HashSet<MockInterview>();
            this.TrainingResources = new HashSet<TrainingResource>();
            this.TrainingSessions = new HashSet<TrainingSession>();
            this.TrainingTrainers = new HashSet<TrainingTrainer>();
            this.WebsiteUserAttendances = new HashSet<WebsiteUserAttendance>();
            this.WebsiteUserTrainings = new HashSet<WebsiteUserTraining>();
            this.WebsiteInvoices = new HashSet<WebsiteInvoice>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int TrainingCourseID { get; set; }
        public string TrainingCourseName { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string TrainingImage { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> StartDate1 { get; set; }
        public Nullable<System.DateTime> EndDate1 { get; set; }
        public Nullable<System.DateTime> StartDate2 { get; set; }
        public Nullable<System.DateTime> EndDate2 { get; set; }
        public Nullable<int> DiscountDate1 { get; set; }
        public Nullable<int> DiscountDate2 { get; set; }
        public Nullable<decimal> FirstPayment { get; set; }
        public Nullable<decimal> SecondPayment { get; set; }
        public string Coupon1 { get; set; }
        public string Coupon2 { get; set; }
        public Nullable<int> DiscountCoupon1 { get; set; }
        public Nullable<int> DiscountCoupon2 { get; set; }
        public string KeyWords { get; set; }
        public string ImgName { get; set; }
        public string ImgPath { get; set; }
        public string FullDescription { get; set; }
        public byte[] FullDescriptionBlob { get; set; }
        public Nullable<decimal> PriceFullPayment { get; set; }
        public Nullable<System.DateTime> LimitFullPaymentDate { get; set; }
        public string SKU { get; set; }
        public string MeetingDetails { get; set; }
        public Nullable<int> Sessions { get; set; }
        public byte[] MeetingDetailsBlob { get; set; }
        public string SpecialAnnouncements { get; set; }
        public byte[] SpecialAnnouncementsBlob { get; set; }
        public string Coupon3 { get; set; }
        public string Coupon4 { get; set; }
        public string Coupon5 { get; set; }
        public Nullable<int> DiscountCoupon3 { get; set; }
        public Nullable<int> DiscountCoupon4 { get; set; }
        public Nullable<int> DiscountCoupon5 { get; set; }
        public Nullable<int> MaxDiscountPayment1 { get; set; }
        public Nullable<int> MaxDiscountTotalPayment { get; set; }
        public Nullable<int> TrainingTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MockInterview> MockInterviews { get; set; }
        public virtual User User { get; set; }
        public virtual TrainingType TrainingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingResource> TrainingResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingSession> TrainingSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingTrainer> TrainingTrainers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteUserAttendance> WebsiteUserAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteUserTraining> WebsiteUserTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteInvoice> WebsiteInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
