//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingTrainer
    {
        public int TrainingTrainerID { get; set; }
        public Nullable<int> TrainingCourseID { get; set; }
        public Nullable<int> TrainerID { get; set; }
    
        public virtual User User { get; set; }
        public virtual TrainingCours TrainingCours { get; set; }
    }
}
