//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebsiteUser()
        {
            this.WebsiteUserDetails = new HashSet<WebsiteUserDetail>();
            this.WebsiteusersAssignments = new HashSet<WebsiteusersAssignment>();
            this.WebsiteUserAttendances = new HashSet<WebsiteUserAttendance>();
            this.WebsiteUserTrainings = new HashSet<WebsiteUserTraining>();
            this.WebsiteInvoices = new HashSet<WebsiteInvoice>();
            this.ResumeSendApprovals = new HashSet<ResumeSendApproval>();
            this.WebsiteUserResumes = new HashSet<WebsiteUserResume>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int WebsiteUserID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string SkypeID { get; set; }
        public string AboutUs { get; set; }
        public string WhyInterested { get; set; }
        public bool AcceptPP { get; set; }
        public Nullable<bool> ReceiveUpdates { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string ProfilePic { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> ConfirmedEmail { get; set; }
        public string Token { get; set; }
        public string RecoveryCode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Ready4Resume { get; set; }
        public Nullable<bool> TakeEvaluation { get; set; }
        public Nullable<bool> EvaluationStatus { get; set; }
        public string RecruiterName { get; set; }
        public Nullable<bool> SignedContract { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteUserDetail> WebsiteUserDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteusersAssignment> WebsiteusersAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteUserAttendance> WebsiteUserAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteUserTraining> WebsiteUserTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteInvoice> WebsiteInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResumeSendApproval> ResumeSendApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteUserResume> WebsiteUserResumes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
