//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteusersAssignment
    {
        public int WebsiteusersAssignmentsID { get; set; }
        public Nullable<int> TrainingCourseID { get; set; }
        public string Path { get; set; }
        public string BackupPath { get; set; }
        public string SessionN { get; set; }
        public Nullable<System.DateTime> DateRecord { get; set; }
        public Nullable<int> WebsiteUserID { get; set; }
        public string OriginalFileName { get; set; }
        public Nullable<double> FileSize { get; set; }
        public string FileExtension { get; set; }
        public byte[] File { get; set; }
    
        public virtual WebsiteUser WebsiteUser { get; set; }
    }
}
