//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteUserResume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebsiteUserResume()
        {
            this.ResumeSendApprovals = new HashSet<ResumeSendApproval>();
        }
    
        public int ResumeID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> WebsiteUserID { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public string Status { get; set; }
        public Nullable<int> SendToID { get; set; }
        public Nullable<bool> Send { get; set; }
        public string FileExtension { get; set; }
        public Nullable<double> FileSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResumeSendApproval> ResumeSendApprovals { get; set; }
        public virtual User User { get; set; }
        public virtual WebsiteUser WebsiteUser { get; set; }
    }
}
