//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteUserTraining
    {
        public int WebsiteUserTrainingID { get; set; }
        public int TrainingCourseID { get; set; }
        public Nullable<int> WebsiteUserID { get; set; }
        public string PayPalID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string TrainingStatus { get; set; }
        public string GUID { get; set; }
        public string payerID { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> Discount { get; set; }
        public string UserInvoiceID { get; set; }
        public string TrainingGroup { get; set; }
    
        public virtual TrainingCours TrainingCours { get; set; }
        public virtual WebsiteUser WebsiteUser { get; set; }
    }
}
