//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteInvoice
    {
        public int WebsiteInvoiceID { get; set; }
        public string BusinessName { get; set; }
        public string BusinessEmail { get; set; }
        public string BusinessFName { get; set; }
        public string BusinessLName { get; set; }
        public string BusinessPhoneCode { get; set; }
        public string BusinessPhoneNumber { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<decimal> ShippingValue { get; set; }
        public string Currency { get; set; }
        public string Note { get; set; }
        public string Terms { get; set; }
        public int WebsiteUserID { get; set; }
        public int TrainingCourseID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PayPalInvoiceID { get; set; }
        public string PayPalID { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> RealAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string BusinessAddress { get; set; }
        public string UserInvoiceID { get; set; }
        public string SKU { get; set; }
    
        public virtual TrainingCours TrainingCours { get; set; }
        public virtual WebsiteUser WebsiteUser { get; set; }
    }
}
