//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteUserAttendance
    {
        public int WebsiteUserAttendanceID { get; set; }
        public int WebsiteUserID { get; set; }
        public int TrainingCourseID { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<System.DateTime> DateRecord { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> Attended { get; set; }
        public string TrainingGroup { get; set; }
    
        public virtual WebsiteUser WebsiteUser { get; set; }
        public virtual TrainingCours TrainingCours { get; set; }
    }
}
